FROM pypy:3.7-7.3-slim

RUN mkdir /api
WORKDIR /api

ADD . /api/

ENV PIP_DEFAULT_TIMEOUT=100
ENV DJANGO_ENV=dev
ENV PORT=5000
ENV PYTHONPATH=/usr/local/bin/pypy
RUN pypy3 -m pip install --upgrade pip
RUN apt update && apt install -y build-essential libpq-dev libssl-dev python-dev
ENV PYTHONPATH=/usr/local/bin/pypy
RUN pip install --trusted-host pypi.org --trusted-host files.pythonhosted.org -r requirements.txt

EXPOSE ${PORT}

CMD pypy manange.py runserver 0.0.0.0:${PORT}

# FROM python:3.8-slim

# RUN mkdir /api
# WORKDIR /api

# ADD . /api/

# ENV PIP_DEFAULT_TIMEOUT=100
# ENV DJANGO_ENV=dev
# ENV PORT=5000
# RUN apt update && apt install -y build-essential
# RUN apt update && apt install -y build-essential libpq-dev libssl-dev python-dev
# RUN pip3 install --trusted-host pypi.org --trusted-host files.pythonhosted.org -r requirements.txt

# EXPOSE ${PORT}

# CMD python manange.py runserver 0.0.0.0:${PORT}
