export const GET_APPLICANTS = Symbol('GET_APPLICANTS');
export const GOT_APPLICANTS = Symbol('GOT_APPLICANTS');
export const GET_APPLICANTS_FAILED = Symbol('GET_APPLICANTS_FAILED');

export const GET_APPLICANT = Symbol('GET_APPLICANT');
export const GOT_APPLICANT = Symbol('GOT_APPLICANT');
export const GET_APPLICANT_FAILED = Symbol('GET_APPLICANT_FAILED');
