# Generated by Django 3.2 on 2021-04-15 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='seats',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
