# Generated by Django 3.2 on 2021-04-15 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210415_1456'),
        ('jobs', '0005_auto_20210415_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='users.company'),
            preserve_default=False,
        ),
    ]
