# Generated by Django 3.2 on 2021-04-15 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_alter_job_salary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='craeted_on',
            new_name='created_on',
        ),
    ]
