# Generated by Django 3.2 on 2021-04-15 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_applicant_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='email',
        ),
        migrations.AddField(
            model_name='applicant',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='applicant', to='users.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='company', to='users.user'),
            preserve_default=False,
        ),
    ]
